== Granite Data Services

==== http://www.graniteds.org

GraniteDS provides server and client libraries that can be used to connect desktop and mobile application
to a server using the AMF3 or JMF serialization protocols, using RPC (remoting) and different messaging
technologies (long-polling, websocket, UDP).

It also provides comprehensive data management features for use with Flex, JavaFX and Android applications.

=== Download

Artifacts are available on http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.graniteds%22[Maven central]
or on http://www.graniteds.org/confluence/display/DOWNLOAD[GraniteDS web site].

=== Licensing

The core GraniteDS libraries and clients (granite-server, granite-client-flex, granite-client-java) are released under the
http://www.gnu.org/licenses/lgpl-2.1-standalone.html[GNU Lesser General Public License, version 2.1].

Advanced libraries (granite-client-flex-advanced, granite-client-javafx, granite-client-android and granite-client-java-advanced)
are released under the http://www.gnu.org/licenses/gpl-3.0-standalone.html[GNU General Public License, version 3.0].
Commercial licenses are also available for these libraries, visit http://www.granitedataservices.com/license
for more details.

=== Documentation

* Java server http://www.graniteds.org/public/docs/3.0.0/docs/java/api/index.html[javadoc]
* Flex client http://www.graniteds.org/public/docs/3.0.0/docs/flex-client/api/index.html[javadoc]
* Java client http://www.graniteds.org/public/docs/3.0.0/docs/java-client/api/index.html[javadoc]
* JavaFX client http://www.graniteds.org/public/docs/3.0.0/docs/javafx-client/api/index.html[javadoc]
* Android client http://www.graniteds.org/public/docs/3.0.0/docs/android-client/api/index.html[javadoc]

* Flex Reference documentation is http://www.graniteds.org/public/docs/3.0.0/docs/reference/flex/en-US/html_single/index.html[here].
* JavaFX Reference documentation is http://www.graniteds.org/public/docs/3.0.0/docs/reference/java/en-US/html_single/index.html[here].

=== Support

You can get community support on the https://groups.google.com/forum/#!forum/graniteds[GraniteDS user forums].

A dedicated http://granitedataservices.com/services/[Commercial support] is also available.

=== Issues

You can report issues via the http://www.graniteds.org/jira/[GraniteDS JIRA].

If you are not sure that what you get is a bug, please ask on the forums before submitting
an issue.

=== Building from sources

GraniteDS uses http://www.gradle.org[Gradle] as build system. You can use the gradle wrapper +./gradlew+ at the root
of the project to run the build.

==== Requirements

JDK 6+ (JDK 7+ recommended for JavaFX), JavaFX 2+ (optional if using JDK 7+).
When using JavaFX 2 on a JDK 6, you will have to copy +jfxrt.jar+ in +JAVA_HOME/jre/lib+.

==== Adobe/Apache Flex requirements

The build of the Flex libraries is optional and requires Flex SDKs 3.6 and 4.5.
Unfortunately due to licensing issues we can't redistribute them or even publish them on a remote repository so
you will have to download them manually and install them in the local maven repository (a Maven 3.x installation
is thus also required):

* http://www.adobe.com/cfusion/entitlement/index.cfm?e=flex3sdk[Download Flex 3.6]
* http://sourceforge.net/adobe/flexsdk/wiki/Download%20Flex%204.5/[Download Flex 4.5]

Then zip them and install them like this:

----
cd /path/to/flex-sdk-3.6
zip -r flex-sdk-3.6.zip flex-sdk-3.6    // Note: on Windows use any GUI zip tool
mvn install:install-file -DgroupId=com.adobe -DartifactId=flex-sdk -Dversion=3.6 -Dpackaging=zip -Dfile=flex-sdk-3.6.zip

cd /path/to/flex-sdk-4.5
zip -r flex-sdk-4.5.zip flex-sdk-4.5    // Note: on Windows use any GUI zip tool
mvn install:install-file -DgroupId=com.adobe -DartifactId=flex-sdk -Dversion=4.5 -Dpackaging=zip -Dfile=flex-sdk-4.5.zip
----

NOTE: You can install any compatible version the Flex SDKs (for example Apache Flex 4.10 for SDK 4.5) but you must use
the version numbers 3.6 and 4.5.

==== Clone GitHub repository

----
git clone git://github.com/graniteds/graniteds.git
----

==== Import projects in a IDE

Projects configuration are provided for Eclipse, you can directly import all subprojects in Eclipse.
Note that the provided project files use Gradle-managed dependencies build path containers and suppose that you are
using the Eclipse Gradle IDE plugin.

==== Quick build (just the libraries, skip tests and API docs)

----
cd graniteds
./gradlew clean build -x test -x javadoc -x asdoc
----

==== Full build

----
cd graniteds
./gradlew clean build
----

===== Adobe/Apache Flex build

The unit tests for Flex require a Flash Player and are skipped when the player path is not defined.
You can define the path to the player with:

----
./gradlew clean build -PflexUnitCommand=/path/to/flashplayer
----

==== Install to local repository

----
./gradlew install
----
