== Source Distribution / Readme
===== +http://www.graniteds.org+ | +http://www.granitedataservices.com+


=== Overview

GraniteDS provides server and client libraries that can be used to connect desktop and mobile applications
to a server using the AMF3 or JMF serialization protocols, through RPC (remoting) and different messaging
technologies (Comet, WebSocket, UDP).

It also provides comprehensive data management features for use with Flex, JavaFX and Android applications.


=== Download

Artifacts are available on http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.graniteds%22[Maven central]
or on http://www.graniteds.org/confluence/display/DOWNLOAD[GraniteDS web site].


=== Licensing

See LICENSES.adoc.


=== Documentation

* Java server http://www.graniteds.org/public/docs/3.0.0/docs/java/api/index.html[javadoc]
* Flex client http://www.graniteds.org/public/docs/3.0.0/docs/flex-client/api/index.html[javadoc]
* Java client http://www.graniteds.org/public/docs/3.0.0/docs/java-client/api/index.html[javadoc]
* JavaFX client http://www.graniteds.org/public/docs/3.0.0/docs/javafx-client/api/index.html[javadoc]
* Android client http://www.graniteds.org/public/docs/3.0.0/docs/android-client/api/index.html[javadoc]

* Flex Reference documentation is http://www.graniteds.org/public/docs/3.0.0/docs/reference/flex/graniteds-refguide-flex.html[here].
* JavaFX Reference documentation is http://www.graniteds.org/public/docs/3.0.0/docs/reference/java/graniteds-refguide-java.html[here].


=== Support

You can get community support on the https://groups.google.com/forum/#!forum/graniteds[GraniteDS user forums].

A dedicated http://granitedataservices.com/services/[Commercial support] is also available.


=== Issues

You can report issues via the http://www.graniteds.org/jira/[GraniteDS JIRA].

If you are not sure that what you get is a bug, please ask on the forums before submitting
an issue.


=== Building from sources

GraniteDS uses http://www.gradle.org[Gradle] as build system. You can use the gradle wrapper +./gradlew+ at the root
of the project to run the build.

==== Requirements

JDK 6+ (JDK 7+ recommended for JavaFX), JavaFX 2+ (optional if using JDK 7+).
When using JavaFX 2 on a JDK 6, you will have to copy +jfxrt.jar+ in +JAVA_HOME/jre/lib+.

==== Adobe/Apache Flex requirements (optional / Flex users only)

The build of the Flex libraries is optional and requires Flex SDKs 3.6 and 4.5 (or above).
Unfortunately due to licensing issues we can't redistribute them or even publish them on a remote repository so
you will have to download them manually and install them in the local maven repository (a Maven 3.x installation
is thus also required):

* http://www.adobe.com/cfusion/entitlement/index.cfm?e=flex3sdk[Download Flex 3.6]
* http://www.adobe.com/devnet/flex/flex-sdk-download.html[Download Flex 4.6]

Then, install them with the following commands:

----
mvn install:install-file -DgroupId=com.adobe -DartifactId=flex-sdk -Dversion=3.6 -Dpackaging=zip -Dfile=flex_sdk_3.6a.zip

mvn install:install-file -DgroupId=com.adobe -DartifactId=flex-sdk -Dversion=4.5 -Dpackaging=zip -Dfile=flex_sdk_4.6.zip
----

If you run into the following error when you build the project: 
----
Error: Could not create toplevel.xml: Cannot run program "/path/to/.gradle/gradleFx/sdks/c38cfb524afcc315b66387e5a36fe4f5c5b91c32/asdoc/templates/asDocHelper" (in directory "[...]"): error=13, Permission denied
----

Just issue this command and relaunch the build process:
----
chmod +x /path/to/.gradle/gradleFx/sdks/c38cfb524afcc315b66387e5a36fe4f5c5b91c32/asdoc/templates/asDocHelper
----

NOTE: You can install any compatible version the Flex SDKs (for example Apache Flex 4.10 for SDK 4.5) but you must use
the version numbers 3.6 and 4.5.

==== Clone GitHub repository

----
git clone git://github.com/graniteds/graniteds.git
----

==== Import projects in a IDE

Projects configuration are provided for Eclipse, you can directly import all subprojects in Eclipse.
Note that the provided project files use Gradle-managed dependencies build path containers and assume that you are
using the Eclipse Gradle IDE plugin.

==== Quick build (just the libraries, skip tests and API docs)

----
cd graniteds
./gradlew clean build -x test -x javadoc -x asdoc
----

==== Full build

----
cd graniteds
./gradlew clean build
----

===== Specifics for the Adobe/Apache Flex build

The unit tests for Flex require a Flash Player and are skipped when the player path is not defined.
You can define the path to the player with:

----
./gradlew clean build -PflexUnitCommand=/path/to/flashplayer
----

==== Install to local repository

----
./gradlew install
----
