/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jboss.seam.example.booking {

    [Bindable]
    [RemoteClass(alias="org.jboss.seam.example.booking.Booking")]
    public class Booking extends BookingBase {
		
		public function get total():Number {
			return hotel.price * nights;
		}
		
		public function get nights():Number {
			return Number((checkoutDate.getTime() - checkinDate.getTime()) / 1000 / 60 / 60 / 24);
		}
		
		public function get name():String {
			return hotel.name;
		}
		
		public function get address():String {
			return hotel.address;
		}
		
		public function get cityState():String {
			return hotel.city + ", " + hotel.state;
		}
    }
}