/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Hotel.as).
 */

package org.jboss.seam.example.booking {

    import flash.events.EventDispatcher;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import flash.utils.getQualifiedClassName;
    import mx.core.IUID;
    import mx.data.utils.Managed;
    import mx.utils.UIDUtil;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;
    import org.granite.tide.IEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class HotelBase implements IExternalizable, IUID {

        [Transient]
        meta var entityManager:IEntityManager = null;

        private var __initialized:Boolean = true;
        private var __detachedState:String = null;

        private var _address:String;
        private var _city:String;
        private var _country:String;
        private var _id:Number;
        private var _name:String;
        private var _price:Number;
        private var _state:String;
        private var _zip:String;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __initialized;

            var property:* = this[name];
            return (
                (!(property is Hotel) || (property as Hotel).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }
        
        [Bindable(event="dirtyChange")]
		public function get meta_dirty():Boolean {
			return Managed.getProperty(this, "meta_dirty", false);
		}

        public function set address(value:String):void {
            _address = value;
        }
        public function get address():String {
            return _address;
        }

        public function set city(value:String):void {
            _city = value;
        }
        public function get city():String {
            return _city;
        }

        public function set country(value:String):void {
            _country = value;
        }
        public function get country():String {
            return _country;
        }

        public function set id(value:Number):void {
            _id = value;
        }
        [Id]
        public function get id():Number {
            return _id;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function set price(value:Number):void {
            _price = value;
        }
        public function get price():Number {
            return _price;
        }

        public function set state(value:String):void {
            _state = value;
        }
        public function get state():String {
            return _state;
        }

        public function set zip(value:String):void {
            _zip = value;
        }
        public function get zip():String {
            return _zip;
        }

        public function set uid(value:String):void {
            // noop...
        }
        public function get uid():String {
            if (isNaN(_id))
                return UIDUtil.createUID();
            return getQualifiedClassName(this) + "#[" + String(_id) + "]";
        }

        meta function merge(em:IEntityManager, obj:*):void {
            var src:HotelBase = HotelBase(obj);
            __initialized = src.__initialized;
            __detachedState = src.__detachedState;
            if (meta::isInitialized()) {
               em.meta_mergeExternal(src._address, _address, null, this, 'address', function setter(o:*):void{_address = o as String}, false);
               em.meta_mergeExternal(src._city, _city, null, this, 'city', function setter(o:*):void{_city = o as String}, false);
               em.meta_mergeExternal(src._country, _country, null, this, 'country', function setter(o:*):void{_country = o as String}, false);
               em.meta_mergeExternal(src._id, _id, null, this, 'id', function setter(o:*):void{_id = o as Number}, false);
               em.meta_mergeExternal(src._name, _name, null, this, 'name', function setter(o:*):void{_name = o as String}, false);
               em.meta_mergeExternal(src._price, _price, null, this, 'price', function setter(o:*):void{_price = o as Number}, false);
               em.meta_mergeExternal(src._state, _state, null, this, 'state', function setter(o:*):void{_state = o as String}, false);
               em.meta_mergeExternal(src._zip, _zip, null, this, 'zip', function setter(o:*):void{_zip = o as String}, false);
            }
            else {
               em.meta_mergeExternal(src._id, _id, null, this, 'id', function setter(o:*):void{_id = o as Number});
            }
        }

        public function readExternal(input:IDataInput):void {
            __initialized = input.readObject() as Boolean;
            __detachedState = input.readObject() as String;
            if (meta::isInitialized()) {
                _address = input.readObject() as String;
                _city = input.readObject() as String;
                _country = input.readObject() as String;
                _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _name = input.readObject() as String;
                _price = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _state = input.readObject() as String;
                _zip = input.readObject() as String;
            }
            else {
                _id = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__initialized);
            output.writeObject(__detachedState);
            if (meta::isInitialized()) {
                output.writeObject((_address is IPropertyHolder) ? IPropertyHolder(_address).object : _address);
                output.writeObject((_city is IPropertyHolder) ? IPropertyHolder(_city).object : _city);
                output.writeObject((_country is IPropertyHolder) ? IPropertyHolder(_country).object : _country);
                output.writeObject((_id is IPropertyHolder) ? IPropertyHolder(_id).object : _id);
                output.writeObject((_name is IPropertyHolder) ? IPropertyHolder(_name).object : _name);
                output.writeObject((_price is IPropertyHolder) ? IPropertyHolder(_price).object : _price);
                output.writeObject((_state is IPropertyHolder) ? IPropertyHolder(_state).object : _state);
                output.writeObject((_zip is IPropertyHolder) ? IPropertyHolder(_zip).object : _zip);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}
