/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.jboss.seam.example.booking {

    [Bindable]
    [RemoteClass(alias="org.jboss.seam.example.booking.User")]
    public class User extends UserBase {
		
		private var _loggedIn:Boolean = false;
		private var _statusMessage:String;
		
		function User(name:String = null, username:String = null, password:String = null) {
			this.name = name;
			this.username = username;
			this.password = password;
		}
		
		public function get loggedIn():Boolean {
			return this._loggedIn;
		}
		
		public function set loggedIn(loggedIn:Boolean):void {
			this._loggedIn = loggedIn;
		}
		
		public function get statusMessage():String {
			return this._statusMessage;
		}
		
		public function set statusMessage(statusMessage:String):void {
			this._statusMessage = statusMessage;
		}
    }
}