/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (EmbAddress.as).
 */

package org.granite.test.tide.data {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
	[RemoteClass(alias="org.granite.tide.test.EmbeddedAddress2")]
    public class EmbeddedAddress2 implements IExternalizable {

        private var _address1:String;
        private var _address2:String;
		private var _location:EmbeddedLocation;

        public function set address1(value:String):void {
            _address1 = value;
        }
        public function get address1():String {
            return _address1;
        }

        public function set address2(value:String):void {
            _address2 = value;
        }
        public function get address2():String {
            return _address2;
        }

        public function set location(value:EmbeddedLocation):void {
            _location = value;
        }
        public function get location():EmbeddedLocation {
            return _location;
        }

        public function readExternal(input:IDataInput):void {
            _address1 = input.readObject() as String;
            _address2 = input.readObject() as String;
            _location = input.readObject() as EmbeddedLocation;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_address1);
            output.writeObject(_address2);
            output.writeObject(_location);
        }
    }
}