/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Versioned.as).
 */

package test.granite.ejb3.entity {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.meta;

    use namespace meta;

    [Bindable]
    public class VersionedBase implements IExternalizable {

        private var _version:Number;

        meta function isInitialized(name:String = null):Boolean {
            return true;
        }

        [Bindable(event="unused")]
        public function get version():Number {
            return _version;
        }

        public function readExternal(input:IDataInput):void {
            if (meta::isInitialized()) {
                _version = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
        }

        public function writeExternal(output:IDataOutput):void {
            if (meta::isInitialized()) {
                output.writeObject(_version);
            }
        }
    }
}