/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {
	import mx.collections.ArrayCollection;
	
	import org.granite.tide.test.Contact;
	import mx.core.Application;
	

	[Name("myComponentGlobal")]
	[Bindable]
    public class MyComponentGlobalGDS471 {
    	
      	[In]
		public var application:Application;

		[In][Out]
        public var globalOutjectedVariable:String;


        [Observer("step1Global")]
		public function initializeGlobal():void {
			globalOutjectedVariable = new String("global string");
		}

        [Observer("step2Global")]
		public function updateGlobal():void {
			globalOutjectedVariable = new String("global 2 string");
		}
    }
}
