/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {
	
	import org.granite.tide.Component;
	import org.granite.tide.seam.Context;
	

	[Name("myComponent5")]
	[Bindable]
    public class MyComponent5 {
    	
    	[In]
    	public var ctx:Context;
    	
    	[In] [Out]
    	public var myQuery:Component;
    	
    	[In(create="true")]
    	public var myPanel5:MyPanel5;
    	
    	[Observer("testEvent")]
    	public function test():void {
    		ctx.application.addChild(myPanel5);
    	}
    }
}
