/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {
	
	import mx.events.PropertyChangeEvent;
	
	import org.granite.ns.tide;
	import org.granite.tide.test.Contact;
	
	use namespace tide;
	

	[Name("myComponentNSOutject")]
    [Bindable]
    public class MyComponentNSOutject {
    	
    	[Out]
    	tide var nscontact:Contact;
    	
    	
    	[Observer("createContact")]
    	tide function myEventHandler():void {
    		nscontact = new Contact();
    		dispatchEvent(PropertyChangeEvent.createUpdateEvent(this, "nscontact", null, nscontact));
    	}
    }
}
