/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {
	
	import org.granite.tide.events.TideContextEvent;
	

	[Bindable]
    public class MyComponentSimpleObserver {
    	
    	public var untypedEvent:int = 0;
    	public var typedEvent:int = 0;
    	
    	
    	[Observer]
    	public function myHandler(event:MyEvent):void {
    		typedEvent++;
    	}
    	
    	[Observer("someEvent")]
    	public function myHandler2(event:TideContextEvent):void {
    		untypedEvent++;
    		event.context.dispatchEvent(new MyEvent());
    	}
    }
}
