/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {
	
	import org.granite.tide.BaseContext;
	import org.granite.tide.test.Contact;
	

	[Bindable]
    public class MyComponentModule1 {
    	
    	public var triggered:Boolean = false;
    	
    	[In(create="true")]
    	public var myVariable:Contact;
    	
    	[In(create="true", global="true")]
    	public var globalVariable:Contact;
    	
    	[In]
    	public var context:BaseContext;
    	
    	[Out]
    	public var outjectedVariable:Contact;
    	
    	[Observer]
    	public function myEventHandler(event:MyEvent):void {
    		triggered = true;
    		dispatchEvent(new MyLocalEvent());
    		
    		context.myLocalVariable = new Contact();
    		
    		outjectedVariable = new Contact();
    	}
    }
}
