/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {

	import org.granite.tide.Context;
	import org.granite.tide.test.Contact;
	

	[Name("subcontext.myComponentInject")]
	[Bindable]
    public class MyComponentInjectGDS482 {
    	    	
    	private var _injectedSetter:Contact;
    	
		[In(create="false")]
		final public function set injectedSetter(contact:Contact):void {
			_injectedSetter = contact;
		}
		
		final public function get injectedSetter():Contact {
			return _injectedSetter;
		}
    }
}
