/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {
	import mx.collections.ArrayCollection;
	
	import org.granite.ns.tide;
	import org.granite.tide.test.Contact;
	

	[Name("myComponentNSInject")]
	[Bindable]
    public class MyComponentNSInject {
    	
    	[In]
    	tide var myComponent:MyComponent;
    	
    	[In]
    	tide var myComponentNoCreate:MyComponentNoCreate;
    	
    	[In]
    	tide var myComponentAutoCreate:MyComponentAutoCreate;
    	
    	[In]
    	tide var injectedCollection:ArrayCollection;
    	
    	[In(create="true")]
    	tide var injectedCollectionCreate:ArrayCollection;
    	
    	[In("injectedCollectionCreate")]
    	tide var injectedCollectionAlias:ArrayCollection;
    	
    	[In]
    	tide var injectedEntity:Contact;
    	
    	[In(create="true")]
    	tide var injectedEntityCreate:Contact;
    }
}
