/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {

	[Name("myComponent3b", scope="conversation")]
    public class MyComponentConversation3 {
    	
    	[In]
    	public var testInjectGlobal:String = null;
    	
    	public var injected:String = null;
    	
    	
    	[Observer("test")]
    	public function test():void {
    		injected = testInjectGlobal;
    	}
    }
}
