/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.framework {
	
	import mx.collections.ArrayCollection;
	import mx.collections.IList;
	import mx.containers.Panel;
	import mx.events.PropertyChangeEvent;
	

	[Name]
    public class MyPanel3 extends Panel implements IList {
		
		private var list:ArrayCollection = new ArrayCollection();
    	
    	public var triggered:Boolean = false;
    	
    	[Observer("someEvent2")]
    	public function eventHandler():void {
    		triggered = true;
    	}
		
		public function toArray():Array {
			return list.toArray();
		}
		public function get length():int {
			return list.length;
		}
		public function getItemAt(index:int, prefetch:int = 0):Object {
			return list.getItemAt(index, prefetch);
		}
		public function getItemIndex(item:Object):int {
			return list.getItemIndex(item);
		}
		public function addItem(item:Object):void {
			list.addItem(item);
		}
		public function addItemAt(item:Object, index:int):void {
			list.addItemAt(item, index);
		}
		public function setItemAt(item:Object, index:int):Object {
			return list.setItemAt(item, index);
		}
		public function removeItemAt(index:int):Object {
			return list.removeItemAt(index);
		}
		public function removeAll():void {
			list.removeAll();
		}
		public function itemUpdated(item:Object, property:Object = null, oldValue:Object = null, newValue:Object = null):void {
			list.itemUpdated(item, property, oldValue, newValue);
		}
    }
}
