/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test {
	import org.granite.tide.BaseContext;
	import org.granite.tide.events.TideResultEvent;
	

	[Name("myComponent", scope="conversation")]
    public class MyComponentConversation {
    	
    	[In]
    	public var context:BaseContext;
    	
    	public var started:Boolean;
    	public var ended:Boolean;
    	
    	[Observer("start")]
    	public function start():void {
    		started = true;
            context.conversation.start(context.test.addAsync(context.test.startResult, 1000));
    	}
    	
    	[Observer("end")]
    	public function end():void {
    		ended = true;
    	}
    }
}
