/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Person.as).
 */

package org.granite.tide.test {
	
	import org.granite.meta;
	import org.granite.tide.IEntityManager;
	

    [Managed]
    [RemoteClass(alias="org.granite.tide.test.Person0")]
    public class Person0 {

		public function Person0(id:Number = NaN, firstName:String = null, lastName:String = null):void {
			this.id = id;
			this.uid = "P" + id;
			this.firstName = firstName;
			this.lastName = lastName;
		}
		
		public var id:Number;
		public var uid:String;
		public var firstName:String;
		public var lastName:String;
		
		meta var entityManager:IEntityManager;
		meta function isInitialized():Boolean { return true; }
    }
}
