/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Person.as).
 */

package org.granite.tide.test {
	
	import org.granite.tide.Component;
	

	[RemoteClass(alias="org.granite.tide.test.PersonService")]
    public class PersonService extends Component {
        
        public function PersonService():void {
            super();
        }
    }
}
