/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Document.as).
 */

package org.granite.example.addressbook.entity.embed {

    import flash.utils.ByteArray;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;

    [Bindable]
    public class DocumentBase implements IExternalizable {

        private var _content:ByteArray;
        private var _contentType:String;
        private var _name:String;

        public function set content(value:ByteArray):void {
            _content = value;
        }
        public function get content():ByteArray {
            return _content;
        }

        public function set contentType(value:String):void {
            _contentType = value;
        }
        public function get contentType():String {
            return _contentType;
        }

        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }

        public function readExternal(input:IDataInput):void {
            _content = input.readObject() as ByteArray;
            _contentType = input.readObject() as String;
            _name = input.readObject() as String;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_content);
            output.writeObject(_contentType);
            output.writeObject(_name);
        }
    }
}