/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package test.granite.ejb3.entity {

    [Bindable]
    [RemoteClass(alias="test.granite.ejb3.entity.Address")]
    public class Address extends AddressBase {
    }
}