/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {
	
	import flash.events.Event;
	import org.granite.tide.events.AbstractTideEvent;
	import org.granite.tide.events.IConversationEvent;
	

    public class MyConversationEvent extends AbstractTideEvent implements IConversationEvent {
		
		public var obj:String;
		
		public function MyConversationEvent(obj:String):void {
			this.obj = obj;
		}
		
		public function get conversationId():String {
			return "test";
		}
		
		public override function clone():Event {
			return new MyConversationEvent(obj);
		}
    }
}
