/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {
	
	import org.granite.tide.BaseContext;
	

	[Bindable]
    public class MyComponentModuleB {
    	
    	[In]
    	public var context:BaseContext;
    	
    	public var triggered1:Boolean = false;
    	public var triggered2:Boolean = false;
    	
    	[Observer("myEvent1")]
    	public function myEvent1Handler():void {
    		triggered1 = true;
    	}
    	
    	[Observer("myEvent2")]
    	public function myEvent2Handler():void {
    		triggered2 = true;
    	}
    }
}
