/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {
	import org.granite.test.tide.Contact;
	

	[Name("myComponentOutject")]
	[Bindable]
    public class MyComponentOutject {
    	
    	[Out]
    	public var contact:Contact;
    	
    	[In] [Out]
    	public var inoutContact1:Contact = new Contact();
    	
    	[In] [Out]
    	public var inoutContact2:Contact = new Contact();
    	
    	[In] [Out]
    	public var inoutContact3:Contact;
    	
    	[Observer("createContact")]
    	public function myEventHandler():void {
    		contact = new Contact();
    	}
    }
}
