/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {
	import org.granite.test.tide.Person;

	[Name("myComponent4b", scope="conversation")]
    public class MyComponentConversation4 {
    	
    	[In]
    	public var testInjectGlobal:Person = null;
    	
    	[Observer("test")]
        public function test():void {
    	}
    }
}
