/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {

	import org.granite.tide.BaseContext;
	import org.granite.tide.events.TideContextEvent;
	import org.granite.tide.events.IEventInterceptor;
	
	[Bindable]
    public class MyEventInterceptor implements IEventInterceptor {
		
		public var before:String;
		public var beforeCtx:BaseContext;
		public var after:String;
		public var afterCtx:BaseContext;
		
		public function beforeDispatch(contextEvent:TideContextEvent):void {
			before = contextEvent.type;
			beforeCtx = contextEvent.context;
		}
		
		public function afterDispatch(contextEvent:TideContextEvent):void {
			after = contextEvent.type;
			afterCtx = contextEvent.context;
		}
    }
}
