/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {

import org.granite.tide.events.TideUIEvent;

import spark.components.Panel;

    [Bindable]
    [Name("myUIComponent")]
    public class MyUIComponent extends Panel {

        public function dispatch():void {
            dispatchEvent(new TideUIEvent("org.test.myManagedEvent", new MyManagedEvent()));
        }
    }
}
