/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.granite.test {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="org.granite.test.Salutation")]
    public class Salutation extends Enum {

        public static const Mr:Salutation = new Salutation("Mr", _);
        public static const Ms:Salutation = new Salutation("Ms", _);
        public static const Dr:Salutation = new Salutation("Dr", _);

        function Salutation(value:String = null, restrictor:* = null) {
            super((value || Mr.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [Mr, Ms, Dr];
        }

        public static function valueOf(name:String):Salutation {
            return Salutation(Mr.constantOf(name));
        }
    }
}