/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {

	[Name("myComponent3a")]
	[Bindable]
    public class MyComponent3 {
    	
    	[In] [Out]
    	public var testInjectGlobal:String = null;
    	
    	
    	[Observer("testGlobal")]
    	[Test]
        public function testGlobal():void {
    		testInjectGlobal = "test";
    	}
    }
}
