/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {
	
	import mx.containers.Panel;
		

	[Name]
    public class MyPanel2 extends Panel {
    	
    	public var triggered:Boolean = false;
    	
    	[Observer("someEvent2")]
    	public function eventHandler():void {
    		triggered = true;
    	}
    }
}
