/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Person.as).
 */

package org.granite.test.tide.data {

    import flash.utils.ByteArray;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.meta;
    import org.granite.test.tide.AbstractEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;
    import org.granite.util.Enum;

    use namespace meta;

    [Managed]
    [RemoteClass(alias="org.granite.test.tide.Consent")]
    public class Consent extends AbstractEntity {

        private var _name:String;
		private var _patient:Patient5;
		private var _documentList:DocumentList;
        
        		
		public function set name(value:String):void {
			_name = value;
		}
		public function get name():String {
			return _name;
		}
		
		public function set patient(value:Patient5):void {
			_patient = value;
		}
		public function get patient():Patient5 {
			return _patient;
		}
		
        public function set documentList(value:DocumentList):void {
			_documentList = value;
        }
        public function get documentList():DocumentList {
            return _documentList;
        }

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:Consent = Consent(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
				em.meta_mergeExternal(src._documentList, _documentList, null, this, 'documentList', function setter(o:*):void{_documentList = o as DocumentList}) as DocumentList;
                em.meta_mergeExternal(src._name, _name, null, this, 'name', function setter(o:*):void{_name = o as String}) as String;
				em.meta_mergeExternal(src._patient, _patient, null, this, 'patient', function setter(o:*):void{_patient = o as Patient5}) as Patient5;
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
				_documentList = input.readObject() as DocumentList;
                _name = input.readObject() as String;
				_patient = input.readObject() as Patient5;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
				output.writeObject((_documentList is IPropertyHolder) ? IPropertyHolder(_documentList).object : _documentList);
                output.writeObject((_name is IPropertyHolder) ? IPropertyHolder(_name).object : _name);
				output.writeObject((_patient is IPropertyHolder) ? IPropertyHolder(_patient).object : _patient);
            }
        }
    }
}
