/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.granite.example.addressbook.cdi.service {

    [RemoteClass(alias="org.granite.example.addressbook.cdi.service.PersonService")]
    public class PersonService extends PersonServiceBase {
    }
    
}
