/**
 * Generated by Gas3 v2.3.1 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (WelcomeService.as).
 */

package org.granite.test.tide.spring {

    import flash.utils.flash_proxy;
    import mx.rpc.AsyncToken;
    import org.granite.collections.IMap;
    import org.granite.tide.BaseContext;
    import org.granite.tide.Component;
    import org.granite.tide.ITideResponder;
    
    use namespace flash_proxy;

	[RemoteClass(alias="com.myapp.services.WelcomeService")]
    public class WelcomeService extends Component {    
        
        public function list(arg0:Object, arg1:int, arg2:int, arg3:Array, arg4:Array, resultHandler:Object = null, faultHandler:Function = null):AsyncToken {
            if (faultHandler != null)
                return callProperty("list", arg0, arg1, arg2, arg3, arg4, resultHandler, faultHandler) as AsyncToken;
            else if (resultHandler is Function || resultHandler is ITideResponder)
                return callProperty("list", arg0, arg1, arg2, arg3, arg4, resultHandler) as AsyncToken;
            else if (resultHandler == null)
                return callProperty("list", arg0, arg1, arg2, arg3, arg4) as AsyncToken;
            else
                throw new Error("Illegal argument to remote call (last argument should be Function or ITideResponder): " + resultHandler);
        }    
        
        public function hello(arg0:String, resultHandler:Object = null, faultHandler:Function = null):AsyncToken {
            if (faultHandler != null)
                return callProperty("hello", arg0, resultHandler, faultHandler) as AsyncToken;
            else if (resultHandler is Function || resultHandler is ITideResponder)
                return callProperty("hello", arg0, resultHandler) as AsyncToken;
            else if (resultHandler == null)
                return callProperty("hello", arg0) as AsyncToken;
            else
                throw new Error("Illegal argument to remote call (last argument should be Function or ITideResponder): " + resultHandler);
        }    
        
        public function findAll(resultHandler:Object = null, faultHandler:Function = null):AsyncToken {
            if (faultHandler != null)
                return callProperty("findAll", resultHandler, faultHandler) as AsyncToken;
            else if (resultHandler is Function || resultHandler is ITideResponder)
                return callProperty("findAll", resultHandler) as AsyncToken;
            else if (resultHandler == null)
                return callProperty("findAll") as AsyncToken;
            else
                throw new Error("Illegal argument to remote call (last argument should be Function or ITideResponder): " + resultHandler);
        }
    }
}
