/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {
	
	import org.granite.test.tide.Contact;
	

	[Bindable]
    public class MyComponentModule1b {
    	
    	public var localTriggered:Boolean = false;
    	
    	[In(create="true")]
    	public var myVariable:Contact;
    	
    	[In]
    	public var myLocalVariable:Contact;
    	
    	[Observer]
    	public function myLocalEventHandler(event:MyLocalEvent):void {
    		localTriggered = true;
    	}
    }
}
