/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.framework {

	import org.flexunit.Assert;
	import org.granite.tide.Context;
	import org.granite.tide.events.TideContextEvent;
	

	[Bindable]
    public class MyComponentInjectGDS844 {
		
		[Inject]
		public var context:Context;
		
		[Inject]
		public var service:MyService;
		
		[Observer]
		public function myEvent(event:MyConversationEvent):void {
		}	
		
		public function end():void {
			context.meta_end();
		} 
    }
}
