:imagesdir: ./images

[[graniteds.messaging]]
== Messaging (Gravity)

Granite Data Services provides a real-time messaging service, code name _Gravity_. It currently provides 
a link:$$http://en.wikipedia.org/wiki/Comet_(programming)$$[Comet]-like implementation with AMF3 data polling over HTTP and 
a link:$$http://datatracker.ietf.org/doc/rfc6455/?include_text=1$$[WebSocket] based implementation. Both can be used with the same producer/consumer based API. 

The Comet implementation is freely inspired from the link:$$http://cometd.com/bayeux/Bayeux$$[Bayeux] protocol specification and adapted from the Jetty 6.1.x 
implementation of a cometd server.  

The WebSocket server implementation uses the native WebSocket capabilities of the deployment application server when available (Tomcat 7.0.29+, GlassFish 3.1.2+, 
Jetty 8.1.1+) or can alternatively use an embedded Jetty server. 

The WebSocket client is a modified version of the Flash WebSocket client developed by Hiroshi Ichikawa (gimite) that can be found 
link:$$https://github.com/gimite/web-socket-js$$[here]. 

The WebSocket client uses by default the Jetty WebSocket client library. 

For a basic sample of GDS/Gravity, download +graniteds-\*\*\*.zip+ and import the +$$examples/graniteds_chat$$+ as a new project in Eclipse. 

ifdef::flex[]
[[messaging.example.flex]]
=== Example usage with Consumer/Producer

GraniteDS messaging relies on two main AS3 components on the Flex side: +org.granite.gravity.Consumer+ and +org.granite.gravity.Producer+. 
These classes reproduce almost exactly the original Adobe Flex link:$$http://livedocs.adobe.com/flex/201/langref/mx/messaging/Consumer.html$$[+Consumer+] 
and link:$$http://livedocs.adobe.com/flex/201/langref/mx/messaging/Producer.html$$[+Producer+] with the specific internal implementation of GraniteDS. 
The only differences are that you must use +topic+ instead of +subtopic+ due to a change introduced in Flex 3.

 Here is a quick example of GDS ++Consumer++/++Producer++ usage: 

[source,actionscript]
----
...
import org.granite.gravity.Consumer;
import org.granite.gravity.Producer;
...
private var consumer:Consumer = null;
private var producer:Producer = null;

private function connect():void {
    consumer = new Consumer();
    consumer.destination = "gravity";
    consumer.topic = "discussion";
    consumer.subscribe();
    consumer.addEventListener(MessageEvent.MESSAGE, messageHandler);

    producer = new Producer();
    producer.destination = "gravity";
    producer.topic = "discussion";
}

private function disconnect():void {
    consumer.unsubscribe();
    consumer.disconnect();
    consumer = null;

    producer.disconnect();
    producer = null;
}

private function messageHandler(event:MessageEvent):void {
    var msg:AsyncMessage = event.message as AsyncMessage;    
    trace("Received message: " + (msg.body as String));
}

private function send(message:String):void {
    var msg:AsyncMessage = new AsyncMessage();
    msg.body = message;
    producer.send(msg);
}
...
----

In this code, the producer sends +String+ messages, which could of course be of any type, and the producer receives +String+ messages as well. 
These +Strings+ are sent in +AsyncMessage+ envelopes, which is the only envelope type allowed in GDS. 

This example can work with either a Comet or a WebSocket channel implementation. The channel definition for Comet would be, assuming the Comet servlet 
is mapped to ++/gravityamf/\*++ (which is the default recommended url mapping): 

[source,xml]
----
<channels>
	<channel-definition id="gravityamf" class="org.granite.gravity.channels.GravityChannel">
	    <endpoint
	        uri="http://{server.name}:{server.port}/{context.root}/gravityamf/amf"
	        class="flex.messaging.endpoints.AMFEndpoint"/>
	</channel-definition>
</channels>
----

For a WebSocket channel, assuming the WebSocket servlet is mapped to ++/websocketamf/\*++ (recommended default): 

[source,xml]
----
<channels>
	<channel-definition id="gravityamf" class="org.granite.gravity.channels.WebSocketChannel">
	    <endpoint
	        uri="http://{server.name}:{server.port}/{context.root}/websocketamf/amf"
	        class="flex.messaging.endpoints.AMFEndpoint"/>
	</channel-definition>
</channels>
----
endif::flex[]

ifdef::java[]
[[messaging.example.java]]
=== Example usage with Consumer/Producer

GraniteDS messaging relies on two main components on the client side: +org.granite.client.messaging.Consumer+ and +org.granite.client.messaging.Producer+. 

Here is a quick example of GDS ++Consumer++/++Producer++ usage with a Comet/long-polling channel: 

[source,java]
----
...
import org.granite.client.messaging.Consumer;
import org.granite.client.messaging.Producer;
...

public void test() {
	HTTPTransport transport = new ApacheAsyncTransport();		
	AMFMessagingChannel channel = new AMFMessagingChannel(transport, "gravityamf", new URI("http://localhost:8080/myapp/gravityamf/amf"));	
	transport.start();
	
    Consumer consumer = new Consumer(channel, "chat", "discussion");
	consumer.addMessageListener(new TopicMessageListener() {
		@Override
		public void onMessage(TopicMessageEvent event) {
			System.out.println(event.getData());
		}
	});
	
	ResponseMessageFuture future = consumer.subscribe(new ResultFaultIssuesResponseListener() {
		@Override
		public void onResult(ResultEvent event) {
			System.out.println("onSubscribeSuccess");
		}

		@Override
		public void onFault(FaultEvent event) {
			System.out.println("onSubscribeFault");
		}

		@Override
		public void onIssue(IssueEvent event) {
			System.out.println("onSubscribeIssue");
		}
	});
	future.get();
	
    producer = new Producer(channel, "chat", "discussion");
	producer.publish("Hello world").get();
	
	Thread.sleep(1000);
}
...
----

In this code, the producer sends +String+ messages, which could of course be of any type, and the producer receives  +String+ messages as well. 

The same with a WebSocket channel: 

[source,java]
----
...
import org.granite.client.messaging.Consumer;
import org.granite.client.messaging.Producer;
...

public void test() {
	WebSocketTransport transport = new JettyWebSocketTransport();		
	AMFMessagingChannel channel = new AMFMessagingChannel(transport, "websocketamf", new URI("http://localhost:8080/myapp/websocketamf/amf"));	
	transport.start();
	
    Consumer consumer = new Consumer(channel, "chat", "discussion");
	consumer.addMessageListener(new TopicMessageListener() {
		@Override
		public void onMessage(TopicMessageEvent event) {
			System.out.println(event.getData());
		}
	});
	
	ResponseMessageFuture future = consumer.subscribe(new ResultFaultIssuesResponseListener() {
		@Override
		public void onResult(ResultEvent event) {
			System.out.println("onSubscribeSuccess");
		}

		@Override
		public void onFault(FaultEvent event) {
			System.out.println("onSubscribeFault");
		}

		@Override
		public void onIssue(IssueEvent event) {
			System.out.println("onSubscribeIssue");
		}
	});
	future.get();
	
    producer = new Producer(channel, "chat", "discussion");
	producer.publish("Hello world").get();
	
	Thread.sleep(1000);
}
...
----
endif::java[]

[[messaging.selectors]]
=== Topics and Selectors

By default all messages sent by a producer are transmitted to all subscribed consumers. In most cases you will want to more finely control how the 
messages are routed. There are two main ways of doing this: the easiest is the topic and the most advanced is by using selectors. 

Topics are a way to divide the destination in many parts. When a producer sends a message on a particular topic, only the consumers attached to this topic 
will receive the message. For example, if you have a destination for quotes, you could have a topic for each country: 

ifdef::flex[]
[source,actionscript]
----
var producer:Producer = new Producer();
producer.destination = "quotes";
producer.topic = "/germany";
producer.send(message);

var consumerGermany:Consumer = new Consumer();
consumerGermany.destination = "quotes";
consumerGermany.topic = "/germany";
consumerGermany.subscribe();

var consumerFrance:Consumer = new Consumer();
consumerFrance.destination = "quotes";
consumerFrance.topic = "/france";
consumerFrance.subscribe();
----
endif::flex[]

ifdef::java[]
[source,java]
----
Producer producer = new Producer(channel, "quotes", "/germany");
producer.publish(message);

Consumer consumerGermany = new Consumer(channel, "quotes", "/germany");
consumerGermany.subscribe(new ResponseListener() { ... }).get();

Consumer consumerFrance = new Consumer(channel, "quotes", "/france");
consumerFrance.subscribe(new ResponseListener() { ... }).get();
----
endif::java[]

Here only +consumerGermany+ will receive the messages published by the producer. Note the slash (/) to start the name of the topic. 
You can define more sections for the topic name and use wildcards (*) and (**) to match a part of the topic. 
For example you could define a hierarchy +/europe/germany+, +/europe/france+, +/america/US+, and define a consumer for the topic +/europe/\*+ that 
will receive only messages for Germany and France. Finally a consumer with +/\*\*+ will receive everything, whatever topic is used by the producer. 

[NOTE]
====
The JMS adapter currently does not support this filtering by topic as this is not a standard feature of JMS and many JMS providers do not support this concept.
The ActiveMQ adapter however does support it.  
====

Topics are a simple way of filtering the message, but in some cases you may want to use more sophisticated rules to route the messages from producers to consumers. 
Gravity uses the concept of message selectors from JMS to do this. It works by defining a SQL-like select string that will define the criteria that a consumer 
wants on the message headers. 

A consumer can specify its message selector before it subscribes to the destination: 

ifdef::flex[]
[source,actionscript]
----
var consumerFrance:Consumer = new Consumer();
consumerFrance.destination = "quotes";
consumerFrance.selector = "COUNTRY = 'France'";
consumerFrance.subscribe();       
----
endif::flex[]

ifdef::java[]
[source,java]
----
Consumer consumerFrance = new Consumer(channel, "quotes", null);
consumerFrance.setSelector("COUNTRY = 'France'");
consumerFrance.subscribe(new ResponseListener() { ... }).get();        
----
endif::java[]

This consumer will receive all messages that have a header named +COUNTRY+ with the value +France+. Many header values can be combined in the selector with 
+AND+ and +OR+, and you can use operators. See link:$$http://download.oracle.com/javaee/1.4/api/javax/jms/Message.html$$[JMS documentation] for details. 

[[messaging.configuration]]
=== Common configuration

There are three main steps to configure Gravity in an application:
 
* Declare the Gravity servlet implementation for your target server in +web.xml+ 
* Declare a messaging service and destination in +services-config.xml+, mapped to a specific channel  definition of type +GravityChannel+ 

[source,xml]
----
<web-app version="2.5" ...>
    ...
    <listener>
        <listener-class>org.granite.config.GraniteConfigListener</listener-class>
    </listener>

    <servlet>
        <servlet-name>GravityServlet</servlet-name>
        <servlet-class>org.granite.gravity.tomcat.GravityTomcatServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>GravityServlet</servlet-name>
        <url-pattern>/gravityamf/*</url-pattern>
    </servlet-mapping>
    ...
</web-app>
----

This declaration is the one specific to the Tomcat application server. See below for all available Gravity servlet implementations. 

[NOTE]
====
The servlet listener definition is important to ensure proper startup and shutdown of the Gravity services, in particular cleanup of used resources. 
====

[source,xml]
----
<services-config>
    <services>
        <service id="messaging-service"
            class="flex.messaging.services.MessagingService"
            messageTypes="flex.messaging.messages.AsyncMessage">
            <adapters>
                <adapter-definition
                    id="default"
                    class="org.granite.gravity.adapters.SimpleServiceAdapter"
                    default="true"/>
            </adapters>

            <destination id="topic">
                <channels>
                    <channel ref="my-gravityamf"/>
                </channels>
            </destination>
        </service>
    </services>

    <channels>
        <channel-definition
            id="my-gravityamf"
            class="org.granite.gravity.channels.GravityChannel">
            <endpoint
                uri="http://{server.name}:{server.port}/{context.root}/gravityamf/amf"
                class="flex.messaging.endpoints.AMFEndpoint"/>
        </channel-definition>
    </channels>
</services-config>
----

Here, we define a +GravityChannel+ (++gravityamf++) and we use it in the destination named ++topic++. 
See above destination usage in <<messaging.example,Consumer/Producer usage>>. 

The topic we have defined uses the default Gravity adapter +SimpleServiceAdapter+ that is a simple fast in-memory message bus. If you need more advanced 
features such as persistent messages or clustering, you should consider using a dedicated messaging implementation such as 
link:$$http://activemq.apache.org/$$[Apache ActiveMQ]. 

The simple adapter exposes two configuration properties:
 
* ++no-local++: default is +true+, if set to +false+ the client producing messages will receive their own messages  
* ++session-selector++: this is an advanced option and instructs Gravity to store the message selector string in the user session. 
    This allows the server part of the application to override the selector string defined by the client +Consumer+ for security reasons or other purpose. 
    The selector is stored and read from the session attribute named +org.granite.gravity.selector.{destinationId}+. 
 

[[messaging.configappserver.comet]]
==== Supported application servers for Comet/long polling

GraniteDS provides a generic servlet implementation that can work in any compliant servlet container. However it will use blocking I/O and thus 
will provide relatively limited scalability. 

Before the release of the Servlet 3.0 specification, there was no standard way of writing asynchronous non blocking servlets and each server provided 
its own specific API (for example Tomcat +CometProcessor+ or Jetty continuations). GraniteDS thus provides implementations of non blocking messaging for 
the most popular application servers. 

Here is the table of the supported implementations: 

[options="header"]
|===============
|Application server|Servlet class|Specific notes
|Tomcat 6.0.18+|+org.granite.gravity.tomcat.GravityTomcatServlet+|Only with APR/NIO enabled (APR highly recommended)
|JBoss 4.2.x|+org.granite.gravity.tomcat.GravityTomcatServlet+|APR/NIO, disable +CommonHeadersFilter+
|Jetty 6.1.x|+org.granite.gravity.jetty.GravityJettyServlet+|Jetty 7 not supported, Jetty 8 using Servlet 3 API
|JBoss 5+|+org.granite.gravity.jbossweb.GravityJBossWebServlet+|Only with APR/NIO enabled (APR highly recommended)
|WebLogic 9.1+|+org.granite.gravity.weblogic.GravityWebLogicServlet+|See WebLogic documentation for configuration tuning
|GlassFish 3.x|+org.granite.gravity.servlet3.GravityAsyncServlet+|Using Servlet 3.0, requires +async-supported+ in +web.xml+
|Tomcat 7.x / Jetty 8.x|+org.granite.gravity.servlet3.GravityAsyncServlet+|Using Servlet 3.0, requires +async-supported+ in +web.xml+
|Any other|+org.granite.gravity.generic.GravityGenericServlet+|Using blocking I/O (no asynchronous support)
|===============

[[messaging.configappserver.websocket]]
==== Supported application servers for WebSocket

There is no standard way before the release of the Servlet 3.1 specification to use WebSockets in Java EE application servers thus GraniteDS provides 
support for native WebSocket implementations on some application servers. 

Here is the table of the supported implementations: 

[options="header"]
|===============
|Application server|Servlet class|Specific notes
|Tomcat 7.0.29+|+org.granite.gravity.tomcat.TomcatWebSocketServlet+|Only with APR/NIO enabled (APR highly recommended)
|Jetty 8.1.1+|+org.granite.gravity.jetty8.JettyWebSocketServlet+|Jetty 7 not supported
|GlassFish 3.1.2+|+org.granite.gravity.glassfish.GlassFishWebSocketServlet+|
|Any other|Embedded Jetty 8.1.1+|Requires another TCP port, not webapp dependent
|===============

ifdef::flex[]
[[messaging.flashpolicy.websocket]]
==== Flash Policy server for WebSocket

The Flash WebSocket implementation requires the use of a Flash socket policy server for security reasons 
(see link:$$http://www.adobe.com/devnet/flashplayer/articles/socket_policy_files.html$$[here]). 

GraniteDS includes a basic Flash policy server than can be started by simply adding the following to your ++web.xml++:  

[source,xml]
----
<context-param>
    <param-name>flashPolicyFileServer-allowDomains</param-name>
    <param-value>*:*</param-value>
</context-param>
<listener>
    <listener-class>org.granite.gravity.websocket.PolicyFileServerListener</listener-class>
</listener>
----

The server accepts two properties:
 
* ++flashPolicyFileServer-port++: the port on which the server listens (by default 843). 
* ++flashPolicyFileServer-allowDomains++: a list of allowed domains separated by commas. It is used to build the requested +cross-domain-policy+ response file. 
endif::flex[]
  
[[messaging.configadvanced]]
==== Advanced configuration

Whichever Gravity servlet implementation is used in your application, the advanced configuration is done in +granite-config.xml+.
Here is a sample Gravity configuration with all default options: 

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE granite-config PUBLIC "-//Granite Data Services//DTD granite-config internal//EN"
    "http://www.graniteds.org/public/dtd/3.0.0/granite-config.dtd">

<granite-config>

    <gravity
        factory="org.granite.gravity.DefaultGravityFactory"
        channel-idle-timeout-millis="1800000"
        long-polling-timeout-millis="20000"
        reconnect-interval-millis="30000"
        reconnect-max-attempts="60">
        
        <thread-pool
            core-pool-size="5"
            maximum-pool-size="20"
            keep-alive-time-millis="10000"
            queue-capacity="2147483647" />
        
    </gravity>

</granite-config>
----

This &lt;gravity&gt; section is purely optional and you may omit it if you accept default values. 

Some explanations about these options:
 
* ++channel-idle-timeout-millis++: the elapsed time after which an idle channel (pure producer or dead client) may be silently unsubcribed and removed by Gravity. 
    Default is 30 minutes. 
* ++long-polling-timeout-millis++: the elapsed time after which an idle connect request is closed, asking the client to reconnect.
    Default is 20 seconds. Note that setting this value isn't supported in Tomcat/APR configurations. 
* +thread-pool+ attributes: all options are standard parameters for the Gravity +ThreadPoolExecutor+ instance. 

All other configuration options are for advanced use only and you should keep default values.	    

[[messaging.configtomcat]]
==== Tomcat and JBoss/Tomcat specific configuration tips

GraniteDS messaging for Tomcat relies on the +org.apache.catalina.CometProcessor+ interface. In order to enable Comet support in Tomcat, you must configure 
an link:$$http://tomcat.apache.org/tomcat-6.0-doc/aio.html$$[APR or NIO connector]. 

At least for now, APR is the easiest to configure and the most reliable. To configure APR, see documentation 
link:$$http://tomcat.apache.org/tomcat-6.0-doc/apr.html$$[here]. 
On Windows(R), it's simply a matter of downloading a native link:$$http://tomcat.heanet.ie/native/$$[dll] and putting it in your +WINDOWS/system32+ directory 
- while other and better configurations are possible. For more recent versions of Tomcat such as the one embedded in JBoss 5 or 6, or Tomcat 7 you will need 
the latest APR library, see link:$$http://tomcat.apache.org/download-native.cgi$$[here]. 

For JBoss 4.2.*, you must comment out a specific filter in the default global +web.xml+ (++$$&lt;JBOSS_HOME&gt;/server/default/deploy/jboss-web.deployer/conf/web.xml$$++): 

[source,xml]
----
...
<!-- Comment this out!
<filter>
  <filter-name>CommonHeadersFilter</filter-name>
  <filter-class>org.jboss.web.tomcat.filters.ReplyHeaderFilter</filter-class>
  <init-param>
    <param-name>X-Powered-By</param-name>
    <param-value>...</param-value>
  </init-param>
</filter>

<filter-mapping>
  <filter-name>CommonHeadersFilter</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
-->
...
----

See above for Tomcat configuration. 

For JBoss 5+ servers, you must use a specific servlet. JBoss 5 implements its own version of Tomcat, named JBossWeb: 

[source,xml]
----
<web-app version="2.5" ...>
    ...
    <servlet>
        <servlet-name>GravityServlet</servlet-name>
        <servlet-class>org.granite.gravity.jbossweb.GravityJBossWebServlet</servlet-class>
        ... (see Tomcat configuration above for options)
    </servlet>
    ...
</web-app>	        
----

Note that you do not need to comment out the +CommonHeadersFilter+ with JBoss 5, but you still need to enable APR. 

[[messaging.jms]]
=== Integration with JMS

The default messaging engine of GraniteDS is embedded in +SimpleServiceAdapter+ and has many limitations. In particular it does not support clustering or 
persistent messages. 
For more robust messaging, it is possible and recommended to integrate with a robust messaging engine such as Apache ActiveMQ. When deploying your application 
in a full Java EE application server, you may also want to configure Gravity to integrate with the built-in messaging engine of your application server 
(such as HornetQ in JBoss AS 7). 

The GraniteDS JMS adapter configuration follows as closely as possible the standard Adobe Flex configuration for the JMS adapter. 
See link:$$http://livedocs.adobe.com/blazeds/1/blazeds_devguide/jms_messaging_1.html$$[here]. 

Here is a sample configuration for a default JBoss installation with a brief description of the different options: 

[source,xml]
----
<adapters>
  <adapter-definition id="jms" class="org.granite.gravity.adapters.JMSServiceAdapter"/>
</adapters>

<destination id="chat-jms">
  <properties>
    <jms>
      <destination-type>Topic</destination-type>
      <!-- Optional: forces usage of simple text messages
      <message-type>javax.jms.TextMessage</message-type>
      -->
      <connection-factory>ConnectionFactory</connection-factory>
      <destination-jndi-name>topic/testTopic</destination-jndi-name>
      <destination-name>TestTopic</destination-name>
      <acknowledge-mode>AUTO_ACKNOWLEDGE</acknowledge-mode>
      <transacted-sessions>false</transacted-sessions>
      <!-- Optional JNDI environment. Specify the external JNDI configuration to access 
        a remote JMS provider. Sample for a remote JBoss server.
      -->
      <initial-context-environment>
        <property>
          <name>Context.SECURITY_PRINCIPAL</name>
          <value>guest</value>
        </property>
        <property>
          <name>Context.SECURITY_CREDENTIALS</name>
          <value>guest</value>
        </property>
        <property>
          <name>Context.PROVIDER_URL</name>
          <value>http://my.host.com:1099</value>
        </property>
        <property>
          <name>Context.INITIAL_CONTEXT_FACTORY</name>
          <value>org.jnp.interfaces.NamingContextFactory</value>
        </property>
        <property>
          <name>Context.URL_PKG_PREFIXES</name>
          <value>org.jboss.naming:org.jnp.interfaces</value>
        </property>
      </initial-context-environment>
    </jms>
    ...
  </properties>
  ...
  <adapter ref="jms"/>
</destination>
----

Comments on configuration options:
 
* +destination-type+ must be +Topic+ for the moment. Queues may be supported later. 
* +message-type+ may be forced to simple text messages by specifying +javax.jms.TextMessage+.             
* +connection-factory+ and +destination-jndi-name+ are the JNDI names respectively of the JMS +ConnectionFactory+ and of the JMS topic. 
* +destination-name+ is just a label but still required. 
* +acknowledge-mode+ can have the standard values accepted by any JMS provider: +$$AUTO_ACKNOWLEDGE$$+, +$$CLIENT_ACKNOWLEDGE$$+, and +$$DUPS_OK_ACKNOWLEDGE$$+. 
* +transacted-sessions+ allows the use of transactions in sessions when set to +true+. 
* ++initial-context-environment++: The +initial-context+ parameters allow to access a remote JMS server by setting the JNDI context options. 

[NOTE]
====
The JMS headers are always copied between client and JMS messages 
====

[WARNING]
====
Durable subscriptions are not yet supported 
====

[[messaging.activemq]]
=== Using an Embedded ActiveMQ

In the case of a simple Tomcat/Jetty installation without JMS provider, or to allow client-to-client messaging with advanced capabilities such as durable messages, 
Gravity can be integrated with an embedded +Apache ActiveMQ+ instance. 

To enable ActiveMQ, just put the +activemq-xx.jar+ in your +WEB-INF/lib+ directory. The necessary message broker will be lazily created on first use, except if the 
property +create-broker+ is set to +false+. The uri of the created ActiveMQ broker will be +vm://adapterId+. 

Here is a sample configuration to use an embedded ActiveMQ provider: 

[source,xml]
----
<adapters>
  <adapter-definition
    id="activemq"
    class="org.granite.gravity.adapters.ActiveMQServiceAdapter"/>
</adapters>

<destination id="chat-activemq">
  <properties>
    <jms>
      <destination-type>Topic</destination-type>
      <!-- Optional: forces usage of simple text messages
      <message-type>javax.jms.TextMessage</message-type>
      -->
      <connection-factory>ConnectionFactory</connection-factory>
      <destination-jndi-name>topic/testTopic</destination-jndi-name>
      <destination-name>TestTopic</destination-name>
      <acknowledge-mode>AUTO_ACKNOWLEDGE</acknowledge-mode>
      <transacted-sessions>false</transacted-sessions>
    </jms>
    
    <server>
      <durable>true</durable>
      <file-store-root>/var/activemq/data</file-store-root>
      <create-broker>true</create-broker>
      <wait-for-start>false</wait-for-start>
    </server>
  </properties>
  ...
  <adapter ref="activemq"/>
</destination>
----

And a sample configuration to use an external ActiveMQ provider: 

[source,xml]
----
<adapters>
  <adapter-definition
    id="activemq"
    class="org.granite.gravity.adapters.ActiveMQServiceAdapter"/>
</adapters>

<destination id="chat-activemq">
  <properties>
    <jms>
      <destination-type>Topic</destination-type>
      <!-- Optional: forces usage of simple text messages
      <message-type>javax.jms.TextMessage</message-type>
      -->
      <connection-factory>ConnectionFactory</connection-factory>
      <destination-jndi-name>topic/testTopic</destination-jndi-name>
      <destination-name>TestTopic</destination-name>
      <acknowledge-mode>AUTO_ACKNOWLEDGE</acknowledge-mode>
      <transacted-sessions>false</transacted-sessions>
    </jms>
    
    <server>
      <broker-url>tcp://activemq-server:61616</broker-url>
    </server>
  </properties>
  ...
  <adapter ref="activemq"/>
</destination>
----

Comments on some configuration options:
 
* The main parameters (++<jms>;...</jms>++) are identical to those used in the default JMS configuration. See <<messaging.jms,above>>. 
* +durable+, if set to +true+, allows for durable messages, stored in the filesystem. The data store directory of ActiveMQ can be specified by 
    the +file-store-root+ parameter. 
* +create-broker+ is optional, as well as the dependant +wait-for-start+ attribute. When +create-broker+ is +false+, creation of the broker is not automatic 
    and has to be done by the application itself. In this case, +wait-for-start+ set to +true+ tells the +ActiveMQConnectionFactory+ to wait for the actual 
    creation of the broker. Please refer to the ActiveMQ documentation for more details on these options. 


[[messaging.servertoclient]]
=== Server to client publishing

There are mostly two kinds of requirements for messaging: client-to-client interactions, that can be easily handled by the ++Consumer++/++Producer++ pattern, 
and server-to-client push that can be done with either the low-level ++Gravity++ API or directly using the JMS API when the JMS adapter is used.  

*Server to client messaging with the low-level Gravity API*

If you use the +SimpleAdapter+, the message sending will have to be done at a lower level and you will need a compilation dependency on the +Gravity+ API.
It's also possible but not recommended to use this low-level API with the JMS and ActiveMQ adapters. 

It first requires to get the +Gravity+ object from the +ServletContext+. It is set as an attribute named +org.granite.gravity.Gravity+. 
When using Spring, Seam 2 or CDI, you can also get this object by injection (see the corresponding documentation). 

Then you can send messages of type +flex.messaging.messages.Message+ by calling the method +gravity.publish(message);+. 

[source,java]
----
Gravity gravity = GravityManager.getGravity(servletContext);
AsyncMessage message = new AsyncMessage();
message.setDestination("my-gravity-destination");
message.setHeader(AsyncMessage.SUBTOPIC_HEADER, "my-topic");
message.setBody("Message content");
gravity.publishMessage(message);    
----

It you need to simulate a publish from the client subscribed in the current session, you can get the +clientId+ in the session attribute named 
+org.granite.gravity.channel.clientId.{destination}+ and set it in the message. 

*Server to Client Messaging with JMS*

Sending messages from the server to clients simply consists of sending JMS messages to the corresponding JMS topic.
Text messages are received as simple text on the client side, object messages are serialized in AMF3 and deserialized and received as typed objects.
The +Gravity+ messaging channel supports lazily loaded collections and objects, exactly as the remoting channel. 

Here is an example on an EJB3 sending a message: 

[source,java]
----
@Stateless
@Local(Test.class)
public class TestBean implements Test {

    @Resource
    SessionContext ctx;

    @Resource(mappedName="java:/ConnectionFactory")
    ConnectionFactory jmsConnectionFactory;

    @Resource(mappedName="topic/testTopic")
    Topic jmsTopic;


    public TestBean() {
       super();
    }

    public void notifyClient(Object object) {
        try {
            Connection connection = jmsConnectionFactory.createConnection();
            Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
            javax.jms.Message jmsMessage = session.createObjectMessage(person);
            MessageProducer producer = session.createProducer(jmsTopic);
            producer.send(jmsMessage);
            session.close();
            connection.close();
        }
        catch (Exception e) {
            log.error("Could not publish notification", e);
        }
    }
}
----

Here is an example on a Seam 2 component sending a message: 

[source,java]
----
@Stateless
@Local(Test.class)
@Name("test")
public class TestBean implements Test {

    private static Logger log = Logger.getLogger(TestBean.class.getName());

    @In
    private TopicPublisher testTopicPublisher;   
    @In 
    private TopicSession topicSession;
  
    public void notifyClient(Serializable object) {
        try {
            testTopicPublisher.publish(topicSession.createObjectMessage(object));
        } 
        catch (Exception e) {
            log.error("Could not publish notification", e);
        }
    }
}
----

*Server to client messaging with Embedded ActiveMQ*

The only difference with standard JMS is that you can get a +ConnectionFactory+ a bit more easily. Also ActiveMQ supports subtopics. 
The name of the topic is built with the following rule:
 
* Without subtopic, the name of the ActiveMQ destination should be the same as defined in the +jms/destination-name+ configuration parameter. 
* With subtopic, the name is the concatenation of the +destination-name+ parameter with the +subtopic+. Wildcards are supported in the +subtopic+ following 
    Flex convention and are converted to the ActiveMQ format (see link:$$http://activemq.apache.org/wildcards.html$$[here]), 
    meaning that +toto.\*\*+ is converted to +toto.>+. 

[source,java]
----
public class Test throws JMSException {
    // adapterId should be the id of the JMS adapter as defined in services-config.xml
    ConnectionFactory f = new ActiveMQConnectionFactory("vm://adapterId");
    Connection connection = jmsConnectionFactory.createConnection();
    Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);

    ActiveMQTopic activeMQTopic= new ActiveMQTopic("destination");
    javax.jms.Message jmsMessage = session.createObjectMessage(person);
    MessageProducer producer = session.createProducer(activeMQTopic);
    producer.send(jmsMessage);

    session.close();
    connection.close();
}
----

[[messaging.security]]
=== Securing Messaging Destinations

Securing messaging destination is very similar to security remoting destinations (see <<remoting.security,here>>) and most concepts apply to messaging 
services as well as remoting services. 

You can for example setup role-based security on a Gravity destination with the following definition in ++services-config.xml++: 

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<services-config>
    <services>
        <service id="messaging-service"
            class="flex.messaging.services.MessagingService"
            messageTypes="flex.messaging.messages.AsyncMessage">
            <adapters>
                <adapter-definition
                    id="default"
                    class="org.granite.gravity.adapters.SimpleServiceAdapter"
                    default="true"/>
            </adapters>
            
            <destination id="restrictedTopic">
                <channels>
                    <channel ref="my-gravityamf"/>
                </channels>
                <security>
                    <security-constraint>
                        <auth-method>Custom</auth-method>
                        <roles>
                            <role>admin</role>
                        </roles>
                    </security-constraint>
                </security>
            </destination>
        </service>
    </services>
    ...
</services-config>
----

In this case, only users with the role +admin+ will be able to subscribe to the topic +restrictedTopic+. 

*Fine-grained per-destination security*

You may write and configure a specific +GravityDestinationSecurizer+ in order to add fine grained security checks for specific actions. 
In particular you can control who can subscribe or publish messages to a particular topic.   

[source,java]
----
public interface GravityDestinationSecurizer extends DestinationSecurizer {
    public void canSubscribe(GravityInvocationContext context)
        throws SecurityServiceException;
    public void canPublish(GravityInvocationContext context)
        throws SecurityServiceException;
}
----

You then have to tell GraniteDS where to use your securizer: 

[source,xml]
----
<services-config>
    <services>
        <service ...>
            <destination id="restrictedDestination">
                ...
                <properties>
                    <securizer>path.to.MyDestinationSecurizer</securizer>
                </properties>
            </destination>
        </service>
    </services>
    ...
</services-config>
----

Your custom implementation of this interface is expected to throw a +SecurityServiceException+ when the user has no right to execute the requested action 
(subscription or publishing). 
You can also override the subscription message in the method +canSubcribe+ if for example you want to force a particular subtopic or selector depending 
on the user access rights and not only rely on the client to define the subscription parameters. 

[source,java]
----
public class CustomDestinationSecurizer implements GravityDestinationSecurizer {
    
    public void canSubscribe(GravityInvocationContext context) throws SecurityServiceException {
        String profile = getProfileForCurrentUser();
        if (profile.equals("limited"))
            throws new SecurityServiceException("Access denied");
        
        if (profile.equals("restricted"))
            ((CommandMessage)context.getMessage()).getHeaders().put("DSSubtopic", "forcedCustomTopic");
    }
    
    public void canPublish(GravityInvocationContext context) throws SecurityServiceException {
        String profile = getProfileForCurrentUser();
        if (profile.equals("limited"))
            throws new SecurityServiceException("Access denied");
    }
}
----

If you have configured a security service, the current thread has already been authenticated at this point, so you are able to get user information 
depending your security implementation. For example, with Spring Security, you can use +SecurityContextHolder.getContext().getAuthentication()+. 
