/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (PersonUpdateEvent.as).
 */

package org.granite.example.addressbook.cdi.event {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import org.granite.example.addressbook.entity.Person;
    import org.granite.tide.events.AbstractTideEvent;

    [Bindable]
    public class PersonUpdateEventBase extends AbstractTideEvent implements IExternalizable {

        private var _person:Person;

        [Bindable(event="unused")]
        public function get person():Person {
            return _person;
        }

        public function readExternal(input:IDataInput):void {
            _person = input.readObject() as Person;
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(_person);
        }
    }
}