/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.tide.test.data {
	
	import org.granite.tide.BaseContext;
	import org.granite.tide.data.Conflicts;
	import org.granite.tide.data.events.TideDataConflictsEvent;
	import org.granite.tide.test.Contact;
	import org.granite.tide.test.Person;
	

	[Name(scope="conversation")]
	[Bindable]
    public class MyComponentConflictConversation {
    	
    	[In]
    	public var context:BaseContext;
		
		public var conflicts:Conflicts;
		
		public var person:Person;
    	
    	[Observer("editPerson")]
    	public function start(person:Person):void {
			this.person = person;
			
			context.addEventListener(TideDataConflictsEvent.DATA_CONFLICTS, conflictsHandler);
			
			person.lastName = "toto";
			var addedContact:Contact = new Contact();
			addedContact.id = 2;
			addedContact.version = 0;
			addedContact.person = person;
			person.contacts.addItem(addedContact);
			var contact:Contact = Contact(person.contacts.getItemAt(0));
			contact.email = "test";
    	}
		
		private function conflictsHandler(event:TideDataConflictsEvent):void {
			conflicts = event.conflicts;
		}
    }
}
