/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Contact.as).
 */

package org.granite.test.tide.data {
	
	import mx.collections.ArrayCollection;
	
	import org.granite.tide.BaseContext;
	import org.granite.tide.events.TideUIConversationEvent;
	import org.granite.test.tide.Contact;
	import org.granite.test.tide.Person;
	

	[Name("baseEntityConversation", scope="conversation")]
	[Bindable]
    public class BaseEntityConversation {
    	
    	[Inject]
    	public var context:BaseContext;
    	
    	[Observer("start")]
    	public function start(person:Person):void {
    		context.person = person;
    		dispatchEvent(new TideUIConversationEvent(context.contextId + "." + person.id, "startConversation", person));
    	}
    	
    	[Observer("endMerge")]
    	public function endMerge():void {
    		dispatchEvent(new TideUIConversationEvent(context.contextId + "." + context.person.id, "endMergeConversation"));
    		context.meta_end(true);
    	}
    	
    	[Observer("endMerge2")]
    	public function endMerge2():void {
    		dispatchEvent(new TideUIConversationEvent(context.contextId + "." + context.person.id, "endMergeConversation2"));
    		context.meta_end(true);
    	}
    }
}
