/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Person.as).
 */

package org.granite.test.tide.data {

    import flash.utils.ByteArray;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.meta;
    import org.granite.test.tide.AbstractEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;
    import org.granite.util.Enum;

    use namespace meta;

    [Managed]
    [RemoteClass(alias="org.granite.test.tide.Diagnosis")]
    public class Diagnosis extends AbstractEntity {

        private var _name:String;
		private var _patient:Patient4;
		private var _visit:Visit2;
        
        		
		public function set name(value:String):void {
			_name = value;
		}
		public function get name():String {
			return _name;
		}
		
		public function set patient(value:Patient4):void {
			_patient = value;
		}
		public function get patient():Patient4 {
			return _patient;
		}
		
		public function set visit(value:Visit2):void {
			_visit = value;
		}
		public function get visit():Visit2 {
			return _visit;
		}

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:Diagnosis = Diagnosis(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
                em.meta_mergeExternal(src._name, _name, null, this, 'name', function setter(o:*):void{_name = o as String}) as String;
				em.meta_mergeExternal(src._patient, _patient, null, this, 'patient', function setter(o:*):void{_patient = o as Patient4}) as Patient4;
				em.meta_mergeExternal(src._visit, _visit, null, this, 'visit', function setter(o:*):void{_visit = o as Visit2}) as Visit2;
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _name = input.readObject() as String;
				_patient = input.readObject() as Patient4;
				_visit = input.readObject() as Visit2;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject((_name is IPropertyHolder) ? IPropertyHolder(_name).object : _name);
				output.writeObject((_patient is IPropertyHolder) ? IPropertyHolder(_patient).object : _patient);
				output.writeObject((_visit is IPropertyHolder) ? IPropertyHolder(_visit).object : _patient);
            }
        }
    }
}
