/*
 *   GRANITE DATA SERVICES
 *   Copyright (C) 2006-2015 GRANITE DATA SERVICES S.A.S.
 *
 *   This file is part of the Granite Data Services Platform.
 *
 *   Granite Data Services is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Lesser General Public
 *   License as published by the Free Software Foundation; either
 *   version 2.1 of the License, or (at your option) any later version.
 *
 *   Granite Data Services is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
 *   General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public
 *   License along with this library; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
 *   USA, or see <http://www.gnu.org/licenses/>.
 */
/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Person.as).
 */

package org.granite.test.tide.data {

    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.meta;
    import org.granite.ns.tide;
    import org.granite.test.tide.AbstractEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;
    use namespace tide;

    [Managed]
    [RemoteClass(alias="org.granite.test.tide.data.Meeting")]
    public class Meeting extends AbstractEntity {

        private var _client:Client;
        private var _user:User2;
       
        
	public function Meeting(id:Number = NaN, version:Number = NaN, client:Client = null, user:User2 = null):void {
		this.id = id;
		if (!isNaN(id))
			this.uid = "P" + id;
		this.version = version;
		this.client = client;
		this.user = user;
	}
		
		public function set client(value:Client):void {
			_client = value;
		}
		public function get client():Client {
			return _client;
		}
		
		public function set user(value:User2):void {
			_user = value;
		}
		public function get user():User2 {
			return _user;
		}

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:Meeting = Meeting(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
                em.meta_mergeExternal(src._client, _client, null, this, 'client', function setter(o:*):void{_client = o as Client}) as Client;
				em.meta_mergeExternal(src._user, _user, null, this, 'user', function setter(o:*):void{_user = o as User2}) as User2;
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
                _client = input.readObject() as Client;
				_user = input.readObject() as User2;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject((_client is IPropertyHolder) ? IPropertyHolder(_client).object : _client);
				output.writeObject((_user is IPropertyHolder) ? IPropertyHolder(_user).object : _user);
            }
        }
    }
}
