/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Person.as).
 */

package org.granite.test.tide.data {

    import flash.utils.ByteArray;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.meta;
    import org.granite.test.tide.AbstractEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;
    import org.granite.util.Enum;

    use namespace meta;

    [Managed]
    [RemoteClass(alias="org.granite.test.tide.PatientStatus")]
    public class PatientStatus extends AbstractEntity {

        private var _deathCauses:ListCollectionView;
        private var _name:String;
		private var _patient:Patient4;
        
        
        public function set deathCauses(value:ListCollectionView):void {
			_deathCauses = value;
        }
		[Lazy]
        public function get deathCauses():ListCollectionView {
            return _deathCauses;
        }
		
        public function set name(value:String):void {
            _name = value;
        }
        public function get name():String {
            return _name;
        }
		
		public function set patient(value:Patient4):void {
			_patient = value;
		}
		public function get patient():Patient4 {
			return _patient;
		}

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:PatientStatus = PatientStatus(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
				em.meta_mergeExternal(src._deathCauses, _deathCauses, null, this, 'deathCauses', function setter(o:*):void{_deathCauses = o as ListCollectionView}) as ListCollectionView;
                em.meta_mergeExternal(src._name, _name, null, this, 'name', function setter(o:*):void{_name = o as String}) as String;
				em.meta_mergeExternal(src._patient, _patient, null, this, 'patient', function setter(o:*):void{_patient = o as Patient4}) as Patient4;
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
				_deathCauses = input.readObject() as ListCollectionView;
                _name = input.readObject() as String;
				_patient = input.readObject() as Patient4;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
				output.writeObject((_deathCauses is IPropertyHolder) ? IPropertyHolder(_deathCauses).object : _deathCauses);
                output.writeObject((_name is IPropertyHolder) ? IPropertyHolder(_name).object : _name);
				output.writeObject((_patient is IPropertyHolder) ? IPropertyHolder(_patient).object : _patient);
            }
        }
    }
}
