/**
 *   GRANITE DATA SERVICES
 *   Copyright (C) 2006-2013 GRANITE DATA SERVICES S.A.S.
 *
 *   This file is part of the Granite Data Services Platform.
 *
 *   Granite Data Services is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Lesser General Public
 *   License as published by the Free Software Foundation; either
 *   version 2.1 of the License, or (at your option) any later version.
 *
 *   Granite Data Services is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
 *   General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public
 *   License along with this library; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
 *   USA, or see <http://www.gnu.org/licenses/>.
 */
/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Person.as).
 */

package org.granite.test.tide.data {

    import flash.utils.ByteArray;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.meta;
    import org.granite.ns.tide;
    import org.granite.test.tide.AbstractEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;
    use namespace tide;

    [Managed]
    [RemoteClass(alias="org.granite.test.tide.Person7b")]
    public class Person7b extends AbstractEntity {

		private var _byteArray:ByteArray;
		private var _byteArrays:ListCollectionView;
        
        
        public function set byteArray(value:ByteArray):void {
        	_byteArray = value;
        }
        public function get byteArray():ByteArray {
        	return _byteArray;
        }
		
		public function set byteArrays(value:ListCollectionView):void {
			_byteArrays = value;
		}
		public function get byteArrays():ListCollectionView {
			return _byteArrays;
		}

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:Person7b = Person7b(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
                em.meta_mergeExternal(src._byteArray, _byteArray, null, this, 'byteArray', function setter(o:*):void{_byteArray = o as ByteArray}) as ByteArray;
				em.meta_mergeExternal(src._byteArrays, _byteArrays, null, this, 'byteArrays', function setter(o:*):void{_byteArrays = o as ListCollectionView}) as ListCollectionView;
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
				_byteArray = input.readObject() as ByteArray;
				_byteArrays = input.readObject() as ListCollectionView;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
                output.writeObject((_byteArray is IPropertyHolder) ? IPropertyHolder(_byteArray).object : _byteArray);
				output.writeObject((_byteArrays is IPropertyHolder) ? IPropertyHolder(_byteArrays).object : _byteArrays);
            }
        }
    }
}
