/*
 *   GRANITE DATA SERVICES
 *   Copyright (C) 2006-2014 GRANITE DATA SERVICES S.A.S.
 *
 *   This file is part of the Granite Data Services Platform.
 *
 *   Granite Data Services is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Lesser General Public
 *   License as published by the Free Software Foundation; either
 *   version 2.1 of the License, or (at your option) any later version.
 *
 *   Granite Data Services is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
 *   General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public
 *   License along with this library; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
 *   USA, or see <http://www.gnu.org/licenses/>.
 */
/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 26 17:58:20 CEST 2008.
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (Person.as).
 */

package org.granite.test.tide.data {

    import flash.utils.ByteArray;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    
    import mx.collections.ListCollectionView;
    
    import org.granite.meta;
    import org.granite.test.tide.AbstractEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;
    import org.granite.util.Enum;

    use namespace meta;

    [Managed]
    [RemoteClass(alias="org.granite.test.tide.Visit3")]
    public class Visit3 extends AbstractEntity {

        private var _name:String;
		private var _patient:Patient4;
		private var _assessments:ListCollectionView;
		private var _date:Date;
        
        		
		public function set name(value:String):void {
			_name = value;
		}
		public function get name():String {
			return _name;
		}
		
		public function set patient(value:Patient4):void {
			_patient = value;
		}
		public function get patient():Patient4 {
			return _patient;
		}
		
        public function set assessments(value:ListCollectionView):void {
			_assessments = value;
        }
		[Lazy]
        public function get assessments():ListCollectionView {
            return _assessments;
        }
		
		public function set date(value:Date):void {
			_date = value;
		}
		
		[NotNull]      
		public function get date():Date {
			return _date;
		}
		
		[Transient]
		public function set dateUTC(value:Date):void {
			this.date = value == null ? null : new Date(value.valueOf() - value.getTimezoneOffset() * 60000);
		}
		
		[Transient]
		public function get dateUTC():Date {
			return date == null ? null : new Date(date.valueOf() + date.getTimezoneOffset() * 60000);
		}

        override meta function merge(em:IEntityManager, obj:*):void {
            var src:Visit3 = Visit3(obj);
            super.meta::merge(em, obj);
            if (meta::isInitialized()) {
				em.meta_mergeExternal(src._assessments, _assessments, null, this, 'assessments', function setter(o:*):void{_assessments = o as ListCollectionView}) as ListCollectionView;
				em.meta_mergeExternal(src._date, _date, null, this, 'date', function setter(o:*):void{_date = o as Date}) as Date;
                em.meta_mergeExternal(src._name, _name, null, this, 'name', function setter(o:*):void{_name = o as String}) as String;
				em.meta_mergeExternal(src._patient, _patient, null, this, 'patient', function setter(o:*):void{_patient = o as Patient4}) as Patient4;
            }
        }

        override public function readExternal(input:IDataInput):void {
            super.readExternal(input);
            if (meta::isInitialized()) {
				_assessments = input.readObject() as ListCollectionView;
				_date = input.readObject() as Date;
                _name = input.readObject() as String;
				_patient = input.readObject() as Patient4;
            }
        }

        override public function writeExternal(output:IDataOutput):void {
            super.writeExternal(output);
            if (meta::isInitialized()) {
				output.writeObject((_assessments is IPropertyHolder) ? IPropertyHolder(_assessments).object : _assessments);
				output.writeObject((_date is IPropertyHolder) ? IPropertyHolder(_date).object : _date);
                output.writeObject((_name is IPropertyHolder) ? IPropertyHolder(_name).object : _name);
				output.writeObject((_patient is IPropertyHolder) ? IPropertyHolder(_patient).object : _patient);
            }
        }
    }
}
