/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package test.granite.ejb3.entity.types {

    import test.granite.ejb3.entity.embed.Document;

    public interface DocumentedEntity {

        function set document(value:Document):void;
        function get document():Document;
    }
}